### ISSUE TITLE
App just doesn’t work

### ISSUE THREAD

**Issue by bgoldca** [itsMeDavidV/Watchla-Support#179] opened 2023-12-21 20:21 UTC
I bought and installed the app yesterday and it just doesn’t work. I’ve paired it with Bluetooth, restarted both my phone and the watch, and every command I send to the car it says sending cm… for a while and then Unexpected Tesla session error. Please try again. If this persists consider re-signing in. Status code 403. I have logged out and back in. Same error. What’s going on?

Getting frustrated.

**Comment by itsMeDavidV** [comment] 2023-12-22 18:47
Hi @bgoldca sorry about that. This is an issue associated with an API transition that is currently taking place in Tesla. [Please see here for more info.](https://x.com/watchlaapp)

Rest assured, we're working on fixing this issue asap.

**Comment by bgoldca** [comment] 2023-12-22 20:24
So when will it start working?On Dec 22, 2023, at 11:47 AM, David Villegas ***@***.***> wrote:﻿
Hi @bgoldca sorry about that. This is an issue associated with an API transition that is currently taking place in Tesla. Please see here for more info.
Rest assured, we're working on fixing this issue asap.

**Comment by itsMeDavidV** [comment] 2024-01-08 05:38
Hi @bgoldca since this is a duplicate of issue #166, you'll want to subscribe to that issue so that you can stay up to date with new updates regarding this issue like this: https://github.com/itsMeDavidV/Watchla-Support/issues/166#issuecomment-1880405214

In the meantime, I'll be closing this in favor of #166

**Closed as completed by itsMeDavidV** 2024-01-08 05:38 UTC

**Comment by bgoldca** [comment] 2024-01-14 22:26
Hi. Just downloaded the update and now I can open the trunk and the other buttons work, hurt when setting up my watch key or says "place key in center console". I do that and nothing happens. There animation Judy continues on my watch forever. What am I doing wrong?Thanks,BenOn Dec 22, 2023, at 11:47 AM, David Villegas ***@***.***> wrote:﻿
Hi @bgoldca sorry about that. This is an issue associated with an API transition that is currently taking place in Tesla. Please see here for more info.
Rest assured, we're working on fixing this issue asap.

**Comment by bgoldca** [comment] 2024-01-18 21:19
As I mentioned, when trying to set up my watchkey I get to the part where it says put your key on the console and the watch just stays in that position (same screen) even when I put the key there. I know the car is recognizing the key because it lets me drive. But I can’t get past that point on the watch. This is with the latest update of the app (as of 1/18/24). Help!Ben On Jan 14, 2024, at 3:25 PM, Ben Goldberg ***@***.***> wrote:﻿Hi. Just downloaded the update and now I can open the trunk and the other buttons work, hurt when setting up my watch key or says "place key in center console". I do that and nothing happens. There animation Judy continues on my watch forever. What am I doing wrong?Thanks,BenOn Dec 22, 2023, at 11:47 AM, David Villegas ***@***.***> wrote:﻿
Hi @bgoldca sorry about that. This is an issue associated with an API transition that is currently taking place in Tesla. Please see here for more info.
Rest assured, we're working on fixing this issue asap.

**Comment by itsMeDavidV** [comment] 2024-01-18 21:44
Hi @bgoldca can you send over your Watchla support code (found in support screen in your watch app) via https://watchla.app/contact so this can be investigated? Please be sure to mention this issue in your message. Thanks!

**Comment by bgoldca** [comment] 2024-01-18 22:11
Support code is wvsCjJ6EA2. Problem is that when setting up watchkey it tells me to place my key card on the console. I place the card there and I know it's there and placed correctly because I'm able to start driving. But the watch never goes beyond that. It just keeps showing the animation of the key being put on the console.
Ben

    On Thursday, January 18, 2024 at 02:44:17 PM MST, David Villegas ***@***.***> wrote:  
 
 


Hi @bgoldca can you send over your Watchla support code (found in support screen in your watch app) via https://watchla.app/contact so this can be investigated? Please be sure to mention this issue in your message. Thanks!
