### ISSUE TITLE
Apple watch empty - no vehicle info

### ISSUE THREAD

**Issue by sergchil-tb** [itsMeDavidV/Watchla-Support#339] opened 2024-03-14 06:12 UTC
![image](https://github.com/itsMeDavidV/Watchla-Support/assets/101388566/9cc9665c-eea9-44b6-a7d5-86ec6dc74f59)

Lattest test flight version 3.7.1(407)

**Comment by itsMeDavidV** [comment] 2024-03-14 06:35
Hey @sergchil-tb thanks for reporting this. Can you send over your Watchla support code via https://watchla.app/contact so we can investigate? 

Please be sure to reference this issue.

**Comment by sergchil-tb** [comment] 2024-03-14 06:39
Done

**Comment by sergchil-tb** [comment] 2024-03-20 17:20
Any news ?

**Comment by itsMeDavidV** [comment] 2024-03-27 16:25
Hi @sergchil-tb sorry for the late reply. After reviewing the error logs associated with your support code I can confirm that you faced a region delegation issue that was prevalent, causing Watchla to not be able to access your vehicle info. We have since adapted to this issue. 

So going forward, I'd recommend updating both the Watchla iOS and watchOS apps. If that doesn't immediately fix your issue in the watch app, open the iOS, confirm that your vehicle info displays properly, then goto `Preferences` and tap `Refresh watch app`.

Lastly, if that doesn't fix the issue for you, you will need to sign out and then sign back in.

Sorry about the inconvenience this has caused you and thanks again for reporting.

**Comment by jampec01** [comment] 2024-04-01 14:43
Hello,

After another issue that I had and was fixed, now I also have this. The Watchla app on the phone is working but on my watch the app is empty. I have tried to reinstall, relog multiple times but it’s the same.

What else can I or we do?

**Comment by drhousedk** [comment] 2024-04-15 11:08
@itsMeDavidV I'm experiencing the same issue. iPhone app looks fine, Watch app looks just like OP, no vehicle info, vehicle list in app is empty. I tried reinstalling the app on the phone and thus on the watch, made no difference. Vehicle list is empty on the watch app. Tried "Refresh watch app", made no difference.

**Comment by bgg71** [comment] 2024-05-02 05:37
Hello, the problem of lack of information on the vehicle is also with me. I have written and explained about the problem many times, but it continues. I have the latest version of the app installed (425). Ask for assistance. I am paying for an application that does not work and this is not correct. The support code is :[redacted]

**Comment by itsMeDavidV** [comment] 2024-05-03 20:33
Hey @bgg71 can you reach out to us directly: https://watchla.app/contact

**Comment by itsMeDavidV** [comment] 2024-05-13 23:14
Hi all, so quick little update: the issue of blank data like @sergchil-tb reported has been fixed in update v3.8 [which is available for download now](https://apps.apple.com/us/app/watchla-for-tesla/id1546599747). Sorry for any inconvenience this has caused. Please reach out if you continue to experience this behavior after updating *the watch app* to v3.8 later.

**Closed as completed** 2024-05-13 23:15 UTC
