### ISSUE TITLE
App fails to start on Watch

### ISSUE THREAD

**Issue by gozmana** [itsMeDavidV/Watchla-Support#369] opened 2024-05-16 12:53 UTC
Not sure how long it's been an issue, just noticed that app is not working on the watch. i've been using it for several years without any issues. issue started before latest iOS and WatchOS updates. i just updated everything: iOS, watchOS and Watchla app. authorized/added virtual key and set all the permissions. after everything was reinstalled and reboot, app asked if notifications should be allowed, i said yes.
spinning watchla logo came up and it doesn't go away. it just sits there and nothing happens. i love the app but can't use it now. please help.
![IMG_2201](https://github.com/itsMeDavidV/Watchla-Support/assets/169923467/e6cc7fd7-14e0-4bb1-84fb-4486ee0da942)

**Comment by tintu42** [comment] 2024-05-16 19:47
Same here.

**Comment by Tigertanz3** [comment] 2024-05-17 07:53
Same here

**Comment by pcartier4** [comment] 2024-05-17 15:33
New user. Same here, in fact never worked on my watch.

**Comment by CassandraMarie** [comment] 2024-05-17 18:09
Hi @gozmana, @tintu42, @Tigertanz3, @pcartier4, we are sorry to hear you are experiencing difficulties. 

If both your iOS and watch OS are updated to version 8.1, we highly recommend:

Step 1: Sign out of your iOS app and re-sign in

Step 2: Re-authenticate your watch OS. You can re-authenticate on your  iOS app via **preferences > authenticate watch app.** 

Step 3: Refresh your watch app. You can do this within the iOS app via **preferences > refresh watch app.** 

Please let me know it this helps!

**Comment by gozmana** [comment] 2024-05-18 03:43
Both iOS and watchOS updated to latest versions. Reinstalled and re-authenticated app several times. Still no luck. App works correctly on the phone.

**Comment by Tigertanz3** [comment] 2024-05-18 05:36
I did the three steps but it’s not working 🤔

**Comment by pcartier4** [comment] 2024-05-18 17:49
Hello,I did all of the step and watch app is still not working.Thanks.PierreLe 17 mai 2024 à 14:09, Cassandra Marie ***@***.***> a écrit :﻿
Hi @gozmana, @tintu42, @Tigertanz3, @pcartier4, we are sorry to hear you are experiencing difficulties.
If both your iOS and watch OS are updated to version 8.1, we highly recommend:
Step 1: Sign out of your iOS app and re-sign in
Step 2: Re-authenticate your watch OS. You can re-authenticate from your iOS app by going to preferences > authenticate watch app.
Step 3: Refresh your watch app. You can do this within the iOS app via preferences > refresh watch app.
Please let me know it this helps!

**Comment by Tigertanz3** [comment] 2024-05-19 05:35
I did the three steps again and it’s still not working. IOS is on Version 17.5 and WatchOS on Version 10.5

**Comment by Tigertanz3** [comment] 2024-05-19 10:42
Please help me with that issue. I would love to use your app, but at this point I can’t use it at all

**Comment by CassandraMarie** [comment] 2024-05-19 23:02
Hi @gozmana, @Tigertanz3, and @pcartier4, we are testing a working solution to this issue in beta with very promising results. The solution should be out in the coming days in a new update.

**Comment by gozmana** [comment] 2024-05-20 03:33
Thank you for update. Keep up posted.

**Comment by gozmana** [comment] 2024-05-23 04:17
I just updated to version 3.8.1. Removed app from watch and re-installed it. Everything is working now. Thank you.

**Comment by itsMeDavidV** [comment] 2024-05-23 04:37
@gozmana Glad to hear that! I apologize for any inconvenience this has caused you. Please let us know if any other issues arise and thank you for reporting this issue in the first place.

**Comment by Tigertanz3** [comment] 2024-05-23 09:10
Now I can not sign in on the watch 😩

**Comment by pcartier4** [comment] 2024-05-23 13:04
Hello,Just updated to version 3.8.1 and the problem is also fixed on my side!Thanks!PierreLe 23 mai 2024 à 00:37, David Villegas ***@***.***> a écrit :﻿
@gozmana Glad to hear that! I apologize for any inconvenience this has caused you. Please let us know if any other issues arise and thank you for reporting this issue in the first place.

**Comment by CassandraMarie** [comment] 2024-05-28 23:42
@Tigertanz3 Are you still experiencing this issue?

**Closed as completed** 2024-05-31 10:36 UTC
