### ISSUE TITLE
Command error 403

### ISSUE THREAD

**Issue by Runheart007** [itsMeDavidV/Watchla-Support#184] opened 2024-01-02 19:57 UTC
Hi Team.

I bought and installed the app today. Also tried everything suggested for the commands to work but no luck at all.

I notice that the comment on the same issue is that the issue is currently with Tesla.

How long before this is sorted? Not really keen to wait for weeks.

Please advise ASAP

Support code: XEcToAj4Ji

**Comment by itsMeDavidV** [comment] 2024-01-08 05:42
Hi @Runheart007 sorry to hear that you're affected by this. A beta app with the fix is out now and we are allowing all who face this issue into the beta. An App Store update will be out as soon as possible.

Also, since this is a duplicate of issue https://github.com/itsMeDavidV/Watchla-Support/issues/166, you'll want to subscribe to that issue so that you can stay up to date with new updates regarding this issue like this: https://github.com/itsMeDavidV/Watchla-Support/issues/166#issuecomment-1880405214

In the meantime, I'll be closing this in favor of https://github.com/itsMeDavidV/Watchla-Support/issues/166

**Closed as completed by itsMeDavidV** 2024-01-08 05:42 UTC

**Comment by itsMeDavidV** [comment] 2024-01-08 05:44
Additionally, an in-app invite to the beta has been sent out to you via your support code. You can find this invite in the Watchla iOS app in the Preferences screen.
