### ISSUE TITLE
Watchla App

### ISSUE THREAD

**Issue by owlshike2** [itsMeDavidV/Watchla-Support#181] opened 2023-12-31 19:49 UTC
I purchased the Watchla App to use my Apple watch for my Tesla and it will not connect to bluetooth. At first it was discoverable by my Tesla but I got error code 403 and it would not connect. Watchla suggested I logoff and relogin, which I did to try again. Afterwords my Tesla no longer discovers my watch/Watchla through bluetooth and I still cannot connect. Requesting a refund.

**Comment by itsMeDavidV** [comment] 2024-01-08 05:37
Hi @owlshike2 sorry to hear that. This is a duplicate of issue #166, you'll want to subscribe to that issue so that you can stay up to date with new updates regarding this issue like this: https://github.com/itsMeDavidV/Watchla-Support/issues/166#issuecomment-1880405214

**Closed as completed by itsMeDavidV** 2024-01-08 05:37 UTC
