### ISSUE TITLE
Still unable to use my App: no vehicles found 

### ISSUE THREAD

**Issue by athynye** [itsMeDavidV/Watchla-Support#259] opened 2024-01-26 22:55 UTC
For weeks now I’ve been unable to use my Watchla App, ever since I logged in via the new API.
“No vehicles found” is all I get.

**Comment by itsMeDavidV** [comment] 2024-01-27 00:44
We're working on this. After an investigation it seems that the wrong error message is being displayed for some folks in cases where they did not enable the minimum required vehicle permissions to use Watchla at sign in.

Eg: if you disallow Watchla to access vehicle information, it will not be able to retrieve vehicle information, as is the case here.

To ensure Watchla works as intended, we recommend ensuring that at minimum you allow Watchla access to:
- Vehicle Information
- Vehicle Commands
- Vehicle Charging Management

You can edit a 3rd party app's access permissions in your Tesla account.

**Comment by athynye** [comment] 2024-01-27 08:06
Thanks
I had to go to my Tesla account, completely delete access to Watchla, then
log in again ticking those boxes you mentioned.
It’s now working. Much appreciated.

Cheers
David Nye

**Comment by comraddan** [comment] 2024-01-27 18:14
Confirmed - removing access from Tesla (via the email they sent when I originally granted access) and then logging back into Watchla and granting Vehicle Information, Vehicle Commands and Vehicle Charging Management I am able to see my car listed again.

**Comment by CassandraMarie** [comment] 2024-05-09 23:08
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.

**Closed as completed by CassandraMarie** 2024-05-09 23:08 UTC
