### ISSUE TITLE
[Fixed] Bluetooth connectivity issue

### ISSUE THREAD

**Issue by Mictang125** [itsMeDavidV/Watchla-Support#136] opened 2023-06-14 02:42 UTC
After model 3 2023.20.4.1 update, the car could not
![IMG_6754](https://github.com/itsMeDavidV/Watchla-Support/assets/136544901/0a663bd7-3458-42ce-b227-b7b7b932a0af)
 detect apple watch for starting the vehicle. I have tried to reset the ble setting on the watch and delete the mobile key from the car screen, but I could not reconnect to the car ble setting. The watch screen froze at initializing after starting to set up the ble connection with the vehicle.

**Comment by itsMeDavidV** [comment] 2023-06-15 16:09
**Edit: For anyone who is facing this issue, please read my comments below. Also this issue has been fixed in v3.4.5**

Hi @Mictang125 can you please send over you Watchla support code along with a link to this issue to https://watchla.app/contact so that this can be investigated? Thanks.

Your Watchla support code can be found by going to Preferences -> Support / Feedback -> Support code

**Comment by borjagomez** [comment] 2023-06-15 18:12
I am having this exact issue after updating my car to 2023.20.4.1. I’ll try to send you the support code.

**Comment by Mictang125** [comment] 2023-06-16 04:14
> Hi @Mictang125 can you please send over you Watchla support code along with a link to this issue to https://watchla.app/contact so that this can be investigated? Thanks.
> 
> Your Watchla support code can be found by going to Preferences -> Support / Feedback -> Support code

Hi @itsMeDavidV  I just sent out the link and support code to contact.

**Comment by itsMeDavidV** [comment] 2023-06-16 06:56
Hi all, this is verified to be a new critical issue caused by recent changes to Tesla vehicle software.

**Rest assured this issue is being diligently addressed**. An investigation is happening, followed by a fix and then Watchla will ask Apple to ship said fix to all as soon as possible in the form of an App Store update.

Updates for this issue will be posted here in this thread or on Twitter: https://twitter.com/WatchlaApp/status/1669596375795785729?s=20

**For now, if you haven't already, Watchla does not recommend updating your vehicle until this issue is resolved.**

Thank you to everyone for your patience and support as this is quickly investigated and resolved.

**Comment by itsMeDavidV** [comment] 2023-06-16 08:57
A possible fix has been uploaded to beta. If you are facing this issue and would like to test this fix in beta, please reach out via https://watchla.app/contact

If you have already reached out about this, an invite email to the beta has already been sent out to you.

**Comment by itsMeDavidV** [comment] 2023-06-16 15:22
Update v3.4.5 should be available on the App Store any minute now. Thank you everyone for reporting this. I am keeping this issue open for others to see.

**Comment by Mictang125** [comment] 2023-06-17 04:51
> Update v3.4.5 should be available on the App Store any minute now. Thank you everyone for reporting this. I am keeping this issue open for others to see.

Thanks for the update. Everything works fine now!

**Comment by itsMeDavidV** [comment] 2023-06-20 21:16
@Mictang125 you're welcome, very glad to hear that!

**Closed as completed** 2024-05-07 18:10 UTC
