### ISSUE TITLE
Bluetooth set up not working

### ISSUE THREAD

**Issue by skim852** [itsMeDavidV/Watchla-Support#120] opened 2023-03-12 14:13 UTC
When try to set up Bluetooth for the first time, the Watch app stuck initializing and won connect

**Comment by itsMeDavidV** [comment] 2023-03-12 19:04
Hi @skim852 sorry to hear that. Can you send over your Watchla support code to david@watchla.app so that I can check any relevant error logs and get back to you with next steps?

Thanks,
-David

**Comment by skim852** [comment] 2023-03-12 19:25
uYmd6LNJHU

Soohan

On Mar 12, 2023, at 12:04 PM, David Villegas ***@***.***> wrote:

﻿

Hi @skim852<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fskim852&data=05%7C01%7C%7Ccb2a690d467e487ae97908db232c98ff%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638142446666279936%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pM2awcUO4mrjYze4YA8fBRhqI1u1lB2SLuJky7SprWE%3D&reserved=0> sorry to hear that. Can you send over your Watchla support code to ***@***.******@***.***> so that I can check any relevant error logs and get back to you with next steps?

Thanks,
-David

**Comment by itsMeDavidV** [comment] 2023-03-13 00:25
Hi @skim852 so after looking at the error logs associated with your support code,  I can confirm that at the vehicle level you're experiencing a bug that a very small number of people are facing. Because this issue is so rare and hard to re-produce I'd like to invite you to Watchla's beta to test an evolving work around to this issue (your invite can be found by going to Preferences -> Beta Invite) so that we can correct this issue for all. Of course, this is completely voluntary (so no pressure), however I will say by participating you will be helping others facing your exact issue.

Additionally after looking at your error logs, the evolving work-around I mentioned above actually seems to have partially worked for you, but I still have a couple of questions:

At any time during the Bluetooth setup:

- Were you shown a screen on the Watchla watch app informing you to place your keycard under the center console?
- Did you have your keycard placed under the center console?

Looking forward to hearing from you,
-David

**Comment by skim852** [comment] 2023-03-13 00:54
Hi,
At my initial set up, I was asked to put the key card under the console and I did. Tesla app sent me a message saying the new device was connected, but Watchla got hung up and finalizing and did not finish the set up.

Soohan

On Mar 12, 2023, at 5:25 PM, David Villegas ***@***.***> wrote:

﻿

Hi @skim852<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fskim852&data=05%7C01%7C%7Cbbf01dea47b941b1f17808db23596be3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638142639184125323%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2FlSiko7NEZ4oGzhMX4deCSyutqGL3Di%2BRjA65UcN7o%3D&reserved=0> so after looking at the error logs associated with your support code, I can confirm that at the vehicle level you're experiencing a bug that a very small number of people are facing. Because this issue is so rare and hard to re-produce I'd like to invite you to Watchla's beta to test an evolving work around to this issue (your invite can be found by going to Preferences -> Beta Invite) so that we can correct this issue for all. Of course, this is completely voluntary (so no pressure), however I will say by participating you will be helping others facing your exact issue.

Additionally after looking at your error logs, the evolving work-around I mentioned above actually seems to have partially worked for you, but I still have a couple of questions:

At any time during the Bluetooth setup:

  *   Were you shown a screen on the Watchla watch app informing you to place your keycard under the center console?
  *   Did you have your keycard placed under the center console?

Looking forward to hearing back from you,
-David

**Comment by itsMeDavidV** [comment] 2023-03-13 01:00
Yup this confirms my suspicions, which helps a lot. Watchla will be making necessary changes asap.

**Comment by itsMeDavidV** [comment] 2023-03-13 15:03
Hi @skim852 so a little update for you here: based off the info you gave Watchla was able to make further changes that I think *could* completely fix this issue for you. Those changes will be in v3.4.2 (276) which is waiting to be reviewed by Apple and once approved will be released to beta. Additionally, you were sent a TestFlight invite email to the beta. Once you enter into beta and Apple approves the version mentioned above, you will be able to test those changes and hopefully all will go smoothly. 

Since it's Monday, it could take up to a day or two for Apple to approve, however it could also take a shorter amount of time, if we're lucky.

**Comment by itsMeDavidV** [comment] 2023-03-14 22:23
Hi @skim852 I'm happy to report that a fix is ready to be tested! An email with additional info on this was sent out to you.

**Comment by skim852** [comment] 2023-03-15 14:14
Installed the updates app and Bluetooth is connected and working.


On Mar 14, 2023, at 3:23 PM, David Villegas ***@***.***> wrote:

﻿

Hi @skim852<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fskim852&data=05%7C01%7C%7C8ff2fc3aa31544d21d1a08db24dabe51%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638144294138017298%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JXewlIuMTm7E2gofeRbF8FgJ7Fkb1OMwJ6v5wowhz98%3D&reserved=0> I'm happy to report that a fix is ready to be tested! An email with additional info on this was sent out to you.

**Comment by itsMeDavidV** [comment] 2023-03-15 15:42
@skim852 That's very good to hear! Thank you for reporting this issue and for providing good feedback.

We'll begin to roll out this update to the App Store so that it can be available for everyone.

**Closed as completed** 2023-03-15 15:42 UTC
