### ISSUE TITLE
Watch not connecting over cellular

### ISSUE THREAD

**Issue by wgransone** [itsMeDavidV/Watchla-Support#183] opened 2024-01-02 03:47 UTC
My model 3 and Y are on 44.30.5 and 44.30.7 and I just downloaded watchla. The connection works fine over Bluetooth but out of that range, it will not perform any actions to the car. I can’t open the trunk or frunk or unlock the doors, the watch app just says error 403. I know this is supposed to work over cellular too right? My watch uses cellular but the app still won’t connect unless it’s bluetooth

**Comment by itsMeDavidV** [comment] 2024-01-08 05:39
Hi @wgransone sorry to hear that. This is a known issue that is actively being addressed. Also, since this is a duplicate of issue https://github.com/itsMeDavidV/Watchla-Support/issues/166, you'll want to subscribe to that issue so that you can stay up to date with new updates regarding this issue like this: https://github.com/itsMeDavidV/Watchla-Support/issues/166#issuecomment-1880405214

In the meantime, I'll be closing this in favor of https://github.com/itsMeDavidV/Watchla-Support/issues/166

**Closed as completed by itsMeDavidV** 2024-01-08 05:39 UTC
